# Generated by Django 4.1 on 2022-08-15 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_member"),
    ]

    operations = [
        migrations.RenameField(
            model_name="member", old_name="pr_text", new_name="self_introduction",
        ),
        migrations.AddField(
            model_name="member",
            name="project_method",
            field=models.CharField(default="대면", max_length=70),
        ),
    ]
